### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by sbaiti** [codejamninja/react-gantt#10]
Failed to compile
./src/App.js
Module not found: Can't resolve 'react-gantt' in 'C:\projects\gantt-diagramm\src'
This error occurred during the build time and cannot be dismissed.

**Comment by sbaiti** [comment]
![image](https://user-images.githubusercontent.com/32718239/39135160-3a262eb2-4710-11e8-8a5a-2f6c3fd88fe2.png)

just can't import it after the installation ( i am using CRA)

**Comment by sbaiti** [comment]
the errorr is in this link :
https://codesandbox.io/s/qlj5mp2l36

**Comment by codejamninja** [comment]
I fixed the bug. Update to the newest version. I'm really sorry about that. It was a result of a major refactor.

Make sure it is at least version `2.1.1`

**Comment by codejamninja** [comment]
Let me know if it works.

**Comment by sbaiti** [comment]
thank you , it work ...
