### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sbaiti** [codejamninja/react-gantt#11]
there are a problem when calling componentWillUnmount

![image](https://user-images.githubusercontent.com/32718239/39434377-5953d2fa-4c90-11e8-8485-27ffcdfae7e3.png)

**Comment by codejamninja** [comment]
5f224880aa668823223958555631cd2e6245e822 should have fixed it.

Update to `2.1.3`

**Comment by sbaiti** [comment]
thank you ....

**Comment by codejamninja** [comment]
No prob
