### ISSUE TITLE
Show monthly view

### ISSUE THREAD

**Issue by Monigingir** [codejamninja/react-gantt#20]
Hello, 

How can I use months in the header -- for example Jan, Feb etc in the header.

**Comment by codejamninja** [comment]
You have to set the `monthFormat` prop to `MMM`

```js
<ReactGantt monthFormat="MMM" />
```

**Comment by codejamninja** [comment]
The chart will not show months unless the timeline is spread out across multiple months, but not spread out over multiple years.

**Comment by Monigingir** [comment]
Hi @codejamninja ,

Thank you, I did set it and across multiple years. it showed like (Jan 16, Jan17) as steps in header. Can I always make the steps as months (MMM YY format) regardless of the timeline spread?

**Comment by codejamninja** [comment]
Correct, you can you any date format in any timeline spread

**Comment by Monigingir** [comment]
How can i do that, could you please provide the code to fix the steps to one month always. because with only MonthFormat it is not working.

**Comment by codejamninja** [comment]
```js
<ReactGantt secondFormat="MMM" minuteFormat="MMM" hourFormat="MMM" dayFormat="MMM" weekFormat="MMM" monthFormat="MMM" yearFormat="MMM" />
```

**Comment by codejamninja** [comment]
It's all in the docs in the README.md file

**Comment by Monigingir** [comment]
Thank you @codejamninja
